### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by joex92** [xXastaspastaXx/Dimensions#2]
I was using version 1.1.11, then I just updated the plugin and now I get this error:
```apache
29.12 03:07:03 [Server] INFO [Dimensions] Enabling Dimensions v1.1.12
29.12 03:07:03 [Server] INFO [DimensionsDebugger] There was an error with Dimensions. The plugin has been disabled. More info:
29.12 03:07:03 [Server] WARN java.lang.ArrayIndexOutOfBoundsException: 3
29.12 03:07:03 [Server] WARN at me.xxastaspastaxx.dimensions.portal.CompletePortal.parseCompletePortal(CompletePortal.java:176)
29.12 03:07:03 [Server] WARN at me.xxastaspastaxx.dimensions.fileHandling.PortalLocations.<init>(PortalLocations.java:50)
29.12 03:07:03 [Server] WARN at me.xxastaspastaxx.dimensions.fileHandling.PortalFiles.<init>(PortalFiles.java:94)
29.12 03:07:03 [Server] WARN at me.xxastaspastaxx.dimensions.fileHandling.Files.<init>(Files.java:10)
29.12 03:07:03 [Server] WARN at me.xxastaspastaxx.dimensions.Main.onEnable(Main.java:36)
29.12 03:07:03 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
29.12 03:07:03 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
29.12 03:07:03 [Server] WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
29.12 03:07:03 [Server] WARN at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501)
29.12 03:07:03 [Server] WARN at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415)
29.12 03:07:03 [Server] WARN at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:471)
29.12 03:07:03 [Server] WARN at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:259)
29.12 03:07:03 [Server] WARN at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:942)
29.12 03:07:03 [Server] WARN at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:180)
29.12 03:07:03 [Server] WARN at java.lang.Thread.run(Thread.java:748)
29.12 03:07:04 [Multicraft] Skipped 28 lines due to rate limit (40/s)
```
Do I have to recreate the portal files?
I'm worried about the already created portals...

**Comment by xXastaspastaXx** [comment]
Your dimensions version is not the latest. Please use the latest version of dimensions.
Also the error is happening because the format in your **./plugins/Dimensions/portalLocations.json** is outdated.
You can fix it by deleted that file and letting Dimensions generate a new one (but you will lose your saved portals) OR you can do it manually (The new format splits portals with **l/l** instead of **/**). You can also send me your file and I can do it for you.

**Comment by joex92** [comment]
oh right, I first used the latest 1.1.13, then I thought that maybe it was something of the version and tried 1.1.12... I'll check that out about the `portalLocations.json` file...

**Comment by joex92** [comment]
well, in the end I "deleted" the file... so yeah, that was the problem... thanks anyways...
