### ISSUE TITLE
portal not taking you anywhere

### ISSUE THREAD

**Issue by tiarnia** [xXastaspastaXx/Dimensions#5]
so our portal builds in the new world but you can only come back you cant go in to the new world with the portal but if i teleport over there and the use the portal you do come back to the world where you built the portal

**Comment by tiarnia** [comment]
so if i delete all the files exept the portal.yml file then reboot then after i get in game reload the plugin it works till i restart the server then i get this 


[17:31:16] [Server thread/INFO]: [Dimensions] Enabling Dimensions v1.2.0
[17:31:16] [Server thread/INFO]: [DimensionsDebugger] Disabling portal: twilight
[17:31:16] [Server thread/INFO]: [DimensionsDebugger] Reason: There is no world twilight and "GenerateNewWorlds" is set to "false"
[17:31:16] [Server thread/INFO]: [DimensionsDebugger] There was an error with Dimensions. The plugin has been disabled. More info:
[17:31:16] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "me.xxastaspastaxx.dimensions.portal.CustomPortal.getFrame()" because the return value of "me.xxastaspastaxx.dimensions.portal.CompletePortal.getPortal()" is null
[17:31:16] [Server thread/WARN]: 	at me.xxastaspastaxx.dimensions.portal.CompletePortal.setup(CompletePortal.java:79)
[17:31:16] [Server thread/WARN]: 	at me.xxastaspastaxx.dimensions.portal.CompletePortal.<init>(CompletePortal.java:73)
[17:31:16] [Server thread/WARN]: 	at me.xxastaspastaxx.dimensions.portal.CompletePortal.parseCompletePortal(CompletePortal.java:209)
[17:31:16] [Server thread/WARN]: 	at me.xxastaspastaxx.dimensions.files.PortalLocations.<init>(PortalLocations.java:61)
[17:31:16] [Server thread/WARN]: 	at me.xxastaspastaxx.dimensions.files.PortalFiles.<init>(PortalFiles.java:102)
[17:31:16] [Server thread/WARN]: 	at me.xxastaspastaxx.dimensions.files.Files.<init>(Files.java:10)
[17:31:16] [Server thread/WARN]: 	at me.xxastaspastaxx.dimensions.Dimensions.onEnable(Dimensions.java:39)
[17:31:16] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[17:31:16] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[17:31:16] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[17:31:16] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518)
[17:31:16] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432)
[17:31:16] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:594)
[17:31:16] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298)
[17:31:16] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069)
[17:31:16] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[17:31:16] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:832)
[17:31:16] [Server thread/INFO]: [Dimensions] Disabling Dimensions v1.2.0

**Comment by tiarnia** [comment]
after re deleting the folder again and re adding the portal file now it loads fine but i still get no world exists but it does exist how do i tell your plugin it exists ?
and why does it work if i reload it but then it never loads after that if i restart 

[17:37:53] [Server thread/INFO]: [DimensionsDebugger] Disabling portal: twilight
[17:37:53] [Server thread/INFO]: [DimensionsDebugger] Reason: There is no world twilight and "GenerateNewWorlds" is set to "false"

**Comment by xXastaspastaXx** [comment]
if you do not have a world management plugin then you need to set the option "GenerateNewWorlds" to true even if the world exists (as explained in the spigotmc.org).
Also i suggest you do no remove files during runtime and only while the plugin is disabled to prevent errors like the one you sent above.
I want to add that the plugin might not work if you unload it and re-load it again, so be carefull with that.

**Comment by tiarnia** [comment]
that did fix it thanks
